# node-port
# exposes our pgsql db in local port 30007
apiVersion: v1
kind: Service
metadata:
  name: pgsql-np
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30007
  selector:
    app: postgres
---
# exposes our server deployment on port 3008
apiVersion: v1
kind: Service
metadata:
  name: server-np
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 5109
      targetPort: 5109
      nodePort: 30008

