apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: f136pix/closest_tech-server:latest
---
# ClusterIp
# assigns a internal ip inside of the kubernetes container for access
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name:  server
      protocol: TCP
      targetPort: 5109
      port: 5109